apiVersion: v1
kind: Secret
metadata:
  name: secret-ai-pipeline-service
  namespace: lunchpick
type: Opaque
stringData:
  DB_PASSWORD: "P@ssw0rd$"
  OPENAI_API_KEY: "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"
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: "AIzaSyBfENgBCKf_OCTMRC9_WyKg03Br1KC0VCI"
  KAKAO_API_KEY: "b588f91e780efc914b282ad7e3688e01"
  LANGCHAIN_API_KEY: ""
