apiVersion: v1
kind: Service
metadata:
  name: ai-pipeline-service
  namespace: lunchpick
spec:
  type: ClusterIP
  selector:
    app: ai-pipeline-service
  ports:
    - port: 80
      targetPort: 8000
