apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: lunchpick
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      imagePullSecrets:
      - name: lunchpick
      containers:
      - name: recommendation-service
        image: hiondal/lunchpick-recommendation-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: cm-common
        - configMapRef:
            name: cm-recommendation-service
        - secretRef:
            name: secret-common
        - secretRef:
            name: secret-recommendation-service
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          periodSeconds: 15
          failureThreshold: 3
