apiVersion: v1
kind: Secret
metadata:
  name: secret-recommendation-service
  namespace: lunchpick
type: Opaque
stringData:
  WEATHER_API_KEY: "1aa5bfca079a20586915b56f29235cc0"
  KAKAO_API_KEY: "b588f91e780efc914b282ad7e3688e01"
