apiVersion: v1
kind: Secret
metadata:
  name: lunchpick
  namespace: lunchpick
  annotations:
    description: "GCR Artifact Registry - token needs periodic refresh"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: PLACEHOLDER
