apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJoaW9uZGFsIiwicGFzc3dvcmQiOiJkY2tyX3BhdF9ZTjd2WV9wWEx2NWpvYVJFWExxeG4tWTNxc1kiLCJhdXRoIjoiYUdsdmJtUmhiRHBrWTJ0eVgzQmhkRjlaVGpkMldWOXdXRXgyTldwdllWSkZXRXh4ZUc0dFdUTnhjMWs9In19fQ==
kind: Secret
metadata:
  name: lunchpick
  namespace: lunchpick
type: kubernetes.io/dockerconfigjson
