apiVersion: v1
kind: Secret
metadata:
  name: secret-common
  namespace: lunchpick
type: Opaque
stringData:
  DB_PASSWORD: "P@ssw0rd$"
  JWT_SECRET: "LGgJY98lCW2pU7Z63+0t6iURIjqFoY5gAAK3kD17ies="
  JWT_ACCESS_TOKEN_VALIDITY: "1800"
  JWT_REFRESH_TOKEN_VALIDITY: "86400"
